-- 30/08/2013 10:35:31 AM VET
-- Order Prepay
CREATE TABLE LVE_OrderPrePaySchedule (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10) NOT NULL, C_PaySchedule_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DiscountAmt NUMERIC NOT NULL, DiscountDate TIMESTAMP NOT NULL, DueAmt NUMERIC NOT NULL, DueDate TIMESTAMP NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) CHECK (IsValid IN ('Y','N')) NOT NULL, LVE_OrderPrePaySchedule_ID NUMERIC(10) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT LVE_OrderPrePaySchedule_Key PRIMARY KEY (LVE_OrderPrePaySchedule_ID))
;

