ALTER TABLE LVE_OrderPrePaySchedule ADD CONSTRAINT FK_OrderPrePayShedule_Order FOREIGN KEY(C_Order_ID)
REFERENCES C_Order (C_Order_ID)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE LVE_OrderPrePaySchedule ADD CONSTRAINT FK_OrderPrePayShedule_PaySchedule FOREIGN KEY(C_PaySchedule_ID)
REFERENCES C_PaySchedule (C_PaySchedule_ID)
ON UPDATE CASCADE ON DELETE RESTRICT;
